# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-27 19:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0003_auto_20180619_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='threads.Subject'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='threads.Subject'),
        ),
    ]
