# Generated by Django 2.1.2 on 2018-12-02 17:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='Type',
            field=models.CharField(choices=[('Bug', 'Bug'), ('New Feature', 'New feature')], default=django.utils.timezone.now, max_length=5),
            preserve_default=False,
        ),
    ]
