# Generated by Django 2.0.6 on 2018-06-19 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazines', '0018_auto_20170606_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magazine',
            name='name',
            field=models.CharField(default='', max_length=254),
        ),
    ]
